#!/bin/bash
#chkconfig: 2345 10 90
#description: service zookeeper
export    JAVA_HOME=/usr/local/jdk8
export    ZOO_LOG_DIR=/usr/local/zookeeper/logs
ZOOKEEPER_HOME=/usr/local/zookeeper/
case  "$1"   in
          start)  su  root   ${ZOOKEEPER_HOME}/bin/zkServer.sh   start;;
          start-foreground)  su  root  ${ZOOKEEPER_HOME}/bin/zkServer.sh    start-foreground;;
          stop)  su  root   ${ZOOKEEPER_HOME}/bin/zkServer.sh   stop;;
          status)  su root  ${ZOOKEEPER_HOME}/bin/zkServer.sh    status;;
          restart)  su root   ${ZOOKEEPER_HOME}/bin/zkServer.sh   restart;;
          upgrade)su root   ${ZOOKEEPER_HOME}/bin/zkServer.sh   upgrade;;
          print-cmd)su root   ${ZOOKEEPER_HOME}/bin/zkServer.sh   print-cmd;;
          *)  echo  "requirestart|start-foreground|stop|status|restart|print-cmd";;
esac
